const kz = () => (
    {
        translation: {
            "tasks" : "Тапсырмалар",
            "task" : "Тапсырма",
            "take_to_work" : "Жұмысқа апарыңыз",
            "in_queeue" : "күту тапсырмасы",
            "my_task" : "Менің тапсырмаларым",
            "in_process" : "Процессте",
            "archieve" : "Мұрағат",
            "author" : "Автор",
            "subject" : "Тақырып",
            "sys_admin":"Жүйе әкімшісі",
            "priority" : "Priority",
            "description" : "Description",
            "details" : "Details",
            "complete" : "Complete",
            "information" : "Information",
            "files" : "Files",
            "history" : "History",
            "upload_files" : "Upload Files",
            "submit" : "Submit",
            "task_done" : "Task Completed",
            "task_in_process" : "Task in Process",
            "no_data_found":"No Data Found",
            "support_service" : "Support Service",
            "active":"Active Tasks",
            "creation_date":"Date of creation",
            "create_task":"Create New Task",
            "redirect":"Redirect",
            "operation" : "Operation",
            "waitting_confirmation" : "Waiting for confirmation",
            "still_in_work" : "Still in work",
            "empty_log":"Empty Log",
            "accept":"Accept",
            "cancel":"Cancel",
            "confirm":"Confirm",
            "low":"Low",
            "middle": "Middle",
            "hight":"Hieght",
            "critical": "Критический",
            "rate_task":"Please rate the quality of the execution of the application, Where 5 is excellent, and 1 is very bad.",
            "placeholder_feedback":"Gives us your feedback",
            "rejection_reason":"Reason for rejecting a task.",
            "ask_cancel_task":"Are you sure you want to cancel this task?",
            "back":"Back",
            "create_application":"Create Application",
            "op_success":"Success",
            "op_failed":"Failed",
            "author_requred":"Author required!",
            "priority_required":"Priority Required!",
            "description_required":"Description Required!",
            "subject_required":"Subject Required!",
            "files_upload":"Files (Optional)",
            "extra_options":"Extra Options",
            "request_accept_text":"Request accompanying text",
            "period_of_execution":"Period Of Execution",
            "extra":"If not completed, the deadline will be calculated<br />automatically proceed from task priority",
            "placeholder_comment":"Comment, type @ to mention the owner or the system administrator"
        }
    }
)