export const ru = () => (
    {
        translation: {
            "tasks": "Задачи",
            "task": "Задача",
            "take_to_work": "Взять в работу ",
            "in_queeue": "В ожидани",
            "my_task": "Мои",
            "in_process": "В работе",
            "archieve": "Архив",
            "author": "Автор",
            "subject": "Тема",
            "sys_admin": "Системный администратор",
            "priority": "Приоритет",
            "description": "Операция",
            "details": "Подробности",
            "complete": "Выполнил",
            "information": "Информация",
            "files": "Файлы",
            "history": "История",
            "upload_files": "Загрузить файлы",
            "submit": "Отправить",
            "task_done": "Задача выполнена",
            "task_in_process": "Задача в процессе",
            "no_data_found": "Данные не найдены",
            "support_service": "Служба поддержки",
            "active": "Активные",
            "creation_date": "Дата создания",
            "create_task": "Создать задачу",
            "redirect": "Перенаправить",
            "operation": "Операция",
            "waitting_confirmation": "Ожидает подтверждения",
            "still_in_work": " Eще в работе",
            "empty_log": "Пустой журнал",
            "accept": "Принять",
            "cancel": "Отклонить",
            "confirm": "Подтвердить",
            "low": "Низкий",
            "middle": "Средний",
            "hight": "Высокий",
            "critical": "Критический",
            "rate_task": "Оцените пажалста качества исполнения заявка, Где 5 отлично, а 1 очень плохо.",
            "placeholder_feedback": "Дает нам ваш отзыв",
            "rejection_reason": "Причина отклонения задачa.",
            "ask_cancel_task": "Вы уверены, что хотите отменить эту задачу?",
            "back": "Назад",
            "create_application": "Создание заявки",
            "op_success": "Завершено успешно!",
            "op_failed": "Не удалось",
            "author_requred": "Автор обязательна!",
            "priority_required": "Приоритет обязательна!",
            "description_required": "Описание обязательна!",
            "subject_required": "тема обязательна!",
            "files_upload": "Файлы (По желанию)",
            "extra_options": "Дополнительные параметры",
            "request_accept_text": "Запросить cопроводительный текст",
            "period_of_execution": "Срок иcполнения",
            "extra": "В случае если не запонено срок будет  расчитан<br /> автоматически исход от приоритета задачи",
            "placeholder_comment": "Комментарий,  введите @ для упоминания автора задачи или системного администратора"
        }
    }
)